# Generated by Django 5.2.7 on 2025-10-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='Titulo',
            new_name='titulo',
        ),
    ]
