# Generated by Django 5.2.1 on 2025-10-29 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        ('tarefas', '0002_rename_descricao_tarefa_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto'),
        ),
    ]
